[default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/',
    'hardhat/=node_modules/hardhat/',
    '@v3-periphery/=lib/v3-periphery/contracts',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts',
    '@uniswap/v3-core/contracts=./contracts',
    'base64-sol/=node_modules/base64-sol/',
    '@uniswap/lib=lib/solidity-lib',
    '@uniswap/v2-core/contracts=lib/v2-core/contracts',
    '@v3-staker/=lib/v3-staker/contracts',
    '@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts',
    '@swap-router-contracts/contracts=lib/swap-router-contracts/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config